---
- name: install ruby gems
  gem:
    name: "{{ item }}"
    # I want this gem to be available in `/usr/...` not `~/.gem...`.
    user_install: no
  with_items: "{{ gem_to_install }}"

- name: uninstall ruby gems
  gem:
    name: "{{ item }}"
    state: absent
    user_install: no
  with_items: "{{ gem_to_uninstall }}"
