---
# This pup is not responsible for installing ruby.
- name: determine if ruby installed
  command: which ruby
  changed_when: no

- name: determine if gem installed
  command: which gem
  changed_when: no

- name: install gem packages
  include_tasks: gem_packages.yml
